export const CONFIG_SUCCESS = 'CONFIG_SUCCESS';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
export const REST_ERROR = 'REST_ERROR';

export const PLACES_SUCCESS = 'PLACES_SUCCESS';
export const TAGS_SUCCESS = 'TAGS_SUCCESS';
export const TYPES_SUCCESS = 'TYPES_SUCCESS';